### ISSUE TITLE
Where did the pull request go?

### ISSUE THREAD

**Issue by Leseratte10** [Chadderz121/wii-ct-code#11]
Like a month ago, I saw a new pull request by DimitriPilot3, fixing some bugs in the ctcode. 

Where did that pull request go? It was not merged (I don't see the fixes in the code), but it disappeared from the pull requests page. 

Why?

**Comment by Chadderz121** [comment]
I'm not sure, it appears as those his account (@DimitriPilot3) no longer exists, presumably causing the pull request to be removed. I believe I still have a copy on my computer though, so I shall still try to merge it when I get chance.

**Comment by DimitriPilot3** [comment]
Whoops.  My account wasn't deleted, it was only made invisible because I was automatically flagged as a bot (non-human) by mistake since last week.  I had clicked links to 3DS exploit repositories (too many times) from a few external websites that publicly showcased them.  I wasn't aware that this also hid my pull request, otherwise I would've contacted Github support earlier to get my account reinstated.

Anyway, all should be good now!
